---
# https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/

name: Build image for BPi-R4 with MTK feed

on:
  workflow_dispatch

env:
  REMOTE_REPOSITORY: ikarishinjigao/bpi-r4-mtk
  REMOTE_BRANCH: main
  # openwrt
  OPENWRT_REPOSITORY: https://github.com/openwrt/openwrt
  OPENWRT_REF: openwrt-24.10
  # mtk-openwrt-feeds
  MEDIATEK_REPOSITORY: https://git01.mediatek.com/openwrt/feeds/mtk-openwrt-feeds
  MEDIATEK_REF: master
  # config
  RELEASE_PREFIX: bpi-r4-mtk


jobs:
  check_commits:
    name: Check Commits
    runs-on: ubuntu-24.04
    outputs:
      latest_commit_sha: ${{ steps.get_sha.outputs.latest_commit_sha }}
    steps:
      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}

      - name: Get the latest commit SHA
        id: get_sha
        run: |
          echo "latest_commit_sha=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "latest_commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  build:
    name: Build BPI-R4 with MTK feed
    needs: [check_commits]
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget curl zstd \
            git libcurl4-openssl-dev

      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}

      - name: Checkout OpenWrt repository
        run: |
          git clone ${{ env.OPENWRT_REPOSITORY }} openwrt;
          cd openwrt;
          git checkout ${{ env.OPENWRT_REF }}

      - name: Checkout MTK OpenWrt feeds repository
        run: |
          git clone ${{ env.MEDIATEK_REPOSITORY }} mtk-openwrt-feeds;
          cd mtk-openwrt-feeds;
          git checkout ${{ env.MEDIATEK_REF }}

      - name: Apply patches
        run: |
          cd mtk-openwrt-feeds;
          curl -SL https://raw.githubusercontent.com/pmarques/openwrt/757ae46379e9968af752f972cb60b1348877fe25/package/kernel/mt76/patches/999-tx-power-fix.patch | tee autobuild/unified/filogic/mac80211/24.10/files/package/kernel/mt76/patches/9999-tx-power-fix.patch

      - name: Run MTK autobuild prepare
        run: |
          cd openwrt;
          bash ../mtk-openwrt-feeds/autobuild/unified/autobuild.sh filogic-mac80211-mt7988_rfb-mt7996 prepare log_file=make

      - name: Copy config from remote repository
        run: |
          cd openwrt;
          cp ../.config .config

      - name: Build the firmware image
        run: |
          cd openwrt;
          make -j $(nproc) defconfig download world

      - name: Compress all packages
        run: |
          cd openwrt;
          tar caf bin/targets/mediatek/filogic/packages.tar.gz bin/targets/mediatek/filogic/packages

      - name: Add config file
        run: |
          cd openwrt;
          cp .config  bin/targets/mediatek/filogic/config-full

      - name: Package output
        run: |
          cd openwrt;
          tar -cvf ../bpi_r4-images.tar bin/targets/mediatek/filogic

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bpi_r4-images
          path: bpi_r4-images.tar

release:
    name: Create release
    needs: [build, check_commits]
    if: needs.build.result == 'success'
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bpi_r4-images

      - name: Extract artifacts
        run: tar xf bpi_r4-images.tar

      - name: Get current date
        run: echo "RELEASE_DATE=$(date +%F)" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@master
        with:
          files: bin/targets/mediatek/filogic/*
          tag_name: ${{ env.RELEASE_PREFIX }}-${{ env.REMOTE_BRANCH }}-${{ env.RELEASE_DATE }}
          name: OpenWRT BPI-R4 with MTK Feed - ${{ env.RELEASE_DATE }}
          body: |
            OpenWrt ref: ${{ env.OPENWRT_REF }}
            Mediatek feed ref: ${{ env.MEDIATEK_REF }}
            Project ref: ${{ needs.check_commits.outputs.latest_commit_sha }}

      - name: Clean up old releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 5
          delete_tags: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
